Jamie:
  Partner: Charlie
  History:
    - 
    - Sam

Sam:
  Partner:
  History:
    - Charlie

Alex:
  Partner: 
  History:
    - Jamie

Charlie:
  Partner: Jamie
  History:
    - 
    - Riley

Ash:
  History:
    - 
  
Riley:


Morgan:
